// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UF.AssessmentProject.Model;

namespace UF.AssessmentProject.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220615133751_UpdateBDf")]
    partial class UpdateBDf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UF.AssessmentProject.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("totalamount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("UF.AssessmentProject.Model.Partner", b =>
                {
                    b.Property<string>("partnerrefno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("partnerkey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("partnerpassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("partnerrefno");

                    b.ToTable("partners");
                });

            modelBuilder.Entity("UF.AssessmentProject.Model.Transaction.itemdetail", b =>
                {
                    b.Property<string>("partneritemref")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<long>("unitprice")
                        .HasColumnType("bigint");

                    b.HasKey("partneritemref");

                    b.HasIndex("OrderId");

                    b.ToTable("itemdetails");
                });

            modelBuilder.Entity("UF.AssessmentProject.Model.Transaction.itemdetail", b =>
                {
                    b.HasOne("UF.AssessmentProject.Model.Order", null)
                        .WithMany("items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("UF.AssessmentProject.Model.Order", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
